-- CreateTable
CREATE TABLE "Popup" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "discountType" TEXT,
    "discountValue" REAL,
    "discountCode" TEXT,
    "autoGenerateCode" BOOLEAN NOT NULL DEFAULT false,
    "hasExpiration" BOOLEAN NOT NULL DEFAULT false,
    "enterShopifyCode" BOOLEAN NOT NULL DEFAULT false,
    "showStickyBar" BOOLEAN NOT NULL DEFAULT false,
    "sidebarWidget" BOOLEAN NOT NULL DEFAULT false,
    "heading" TEXT,
    "description" TEXT,
    "emailPlaceholder" TEXT,
    "primaryButton" TEXT,
    "secondaryButton" TEXT,
    "footerText" TEXT,
    "logoUrl" TEXT,
    "logoWidth" INTEGER DEFAULT 35,
    "displaySize" TEXT DEFAULT 'standard',
    "alignment" TEXT DEFAULT 'center',
    "cornerRadius" TEXT DEFAULT 'standard',
    "imagePosition" TEXT DEFAULT 'left',
    "hideOnMobile" BOOLEAN NOT NULL DEFAULT false,
    "backgroundOnMobile" BOOLEAN NOT NULL DEFAULT false,
    "imageUrl" TEXT,
    "views" INTEGER NOT NULL DEFAULT 0,
    "subscribers" INTEGER NOT NULL DEFAULT 0,
    "conversionRate" REAL NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
